# Основы веб-скрапинга

Автор: **Булыгин Олег**
* [Я в LinkedIn](https://www.linkedin.com/in/obulygin/)  
* [Мой канал в ТГ по Python](https://t.me/pythontalk_ru)
* [Чат канала](https://t.me/pythontalk_chat)
* [Блог в Телетайпе](https://teletype.in/@pythontalk)

Процесс автоматизированного получения/извлечения информации с веб-ресурсов называется **web-scraping** (рус. веб-скрейпинг/веб-скрапинг).

Какие данные можно извлечь в процессе веб-скрапинга?

- цены и другую информацию о товарах конкурентов;
- сообщения на новостных ресурсах;
- отзывы о товарах/услугах компании на различных площадках;
- и многое другое.

Когда мы открываем интернет-страницу – то, что мы видим это заслуга браузера. Как браузер получает эту информацию и как отображает?

Чтобы это понять, нужно ознакомиться со следующими понятиями:
- **HTTP**;
- **HTML**.

## HTTP
HTTP — это протокол клиент-серверного взаимодействия, позволяющий получать различные ресурсы, например HTML-документы. Протокол HTTP лежит в основе обмена данными в интернете.

Клиенты и серверы взаимодействуют, обмениваясь одиночными сообщениями
(а не потоком данных).

Сообщения, отправленные клиентом (например, веб-браузером), называются **запросами**, а сообщения, отправленные сервером – **ответами**.

Для того чтобы указать серверу на то, какое действие мы хотим произвести с ресурсом, в протоколе HTTP используются так называемые [методы](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP).

Нас в первую очередь интересует метод GET, который запрашивает информацию из указанного источника и не может влиять на его содержимое.

При помощи данного метода мы сможеш получать html-разметку страницы.

## HTML

HTML (англ. HyperText Markup Language, рус. язык гипертекстовой разметки) — стандартизированный язык разметки документов в интернете. Большинство веб-страниц содержат описание разметки на языке HTML. Язык HTML интерпретируется браузерами.

Разметка на языке HTML делается с помощью так называемых тегов, которые помещаются в угловые скобки, и применяется к элементам, заключённым внутри них.

Разметка небольшой страницы выглядит примерно так:
```html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>Название страницы</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <h1> Это заголовок страницы </h1>
        <p> Какой-то текст </p>
    </body>
</html>
```

Обратите внимание, что теги образуют иерархическую структуру, то есть одни теги расположены внутри других. В примере выше тег `<p> … </p>` находится внутри тега `<body> … </body>`.

Кроме того, у тегов могут быть атрибуты, которые пишутся внутри открывающегося тега. Самые популярные атрибуты — это `class` и `id`:
```html
<h1 id="big-title"> Заголовок страницы </h1>
<p class="red-back"> Какой-то текст </p>
```

Изучение языка HTML находится вне рамок этого курса, но на текущий момент нам достаточно понимать, что:

- существуют теги с разными именами;
- у тегов бывают атрибуты, такие как `class` и `id`;
- теги образуют иерархическую структуру, то есть одни теги вложены в другие.

## requests

Чтобы получить код интересующей нас веб-страницы необходимо отправить GET-запрос с помощью библиотеки requests и посмотреть на текст ответа на запрос.

Requests — это библиотека, которую вы можете использовать для отправки всех видов HTTP-запросов. У нее много функций, начиная от передачи параметров в URL-адресах до отправки пользовательских заголовков и проверки SSL.

Документация: https://requests.readthedocs.io/en/master/user/quickstart/

In [ ]:
import requests

In [ ]:
res = requests.get('https://books.toscrape.com/')
# res
res.text

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:29" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.ico" />\n        \n\n        \n        \n    \n    \n        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css" />\n    \n    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />\n    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css" />\n\n\n        \n        \n\n        \n\n        \n            \n            \n\n        \n    </head>\n\n    <body id="default" class="default">\n        \n        \n    \n    \n    <header class="header container-fluid">\n        <div class="page_inner">\n            <div class="row">\n                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>\n</div>\n\n                \n            </div>\n        </div>\n    </header>\n\n    \n    \n<div class="container-fluid page">\n    <div class="page_inner">\n        \n    <ul class="breadcrumb">\n        <li>\n            <a href="index.html">Home</a>\n        </li>\n        <li class="active">All products</li>\n    </ul>\n\n        <div class="row">\n\n            <aside class="sidebar col-sm-4 col-md-3">\n                \n                <div id="promotions_left">\n                    \n                </div>\n                \n    \n    \n        \n        <div class="side_categories">\n            <ul class="nav nav-list">\n                \n                    <li>\n                        <a href="catalogue/category/books_1/index.html">\n                            \n                                Books\n                            \n                        </a>\n\n                        <ul>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/travel_2/index.html">\n                            \n                                Travel\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/mystery_3/index.html">\n                            \n                                Mystery\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical-fiction_4/index.html">\n                            \n                                Historical Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sequential-art_5/index.html">\n                            \n                                Sequential Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/classics_6/index.html">\n                            \n                                Classics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/philosophy_7/index.html">\n                            \n                                Philosophy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/romance_8/index.html">\n                            \n                                Romance\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/womens-fiction_9/index.html">\n                            \n                                Womens Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fiction_10/index.html">\n                            \n                                Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/childrens_11/index.html">\n                            \n                                Childrens\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/religion_12/index.html">\n                            \n                                Religion\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/nonfiction_13/index.html">\n                            \n                                Nonfiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/music_14/index.html">\n                            \n                                Music\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/default_15/index.html">\n                            \n                                Default\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science-fiction_16/index.html">\n                            \n                                Science Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sports-and-games_17/index.html">\n                            \n                                Sports and Games\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/add-a-comment_18/index.html">\n                            \n                                Add a comment\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fantasy_19/index.html">\n                            \n                                Fantasy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/new-adult_20/index.html">\n                            \n                                New Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/young-adult_21/index.html">\n                            \n                                Young Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science_22/index.html">\n                            \n                                Science\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/poetry_23/index.html">\n                            \n                                Poetry\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/paranormal_24/index.html">\n                            \n                                Paranormal\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/art_25/index.html">\n                            \n                                Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/psychology_26/index.html">\n                            \n                                Psychology\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/autobiography_27/index.html">\n                            \n                                Autobiography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/parenting_28/index.html">\n                            \n                                Parenting\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/adult-fiction_29/index.html">\n                            \n                                Adult Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/humor_30/index.html">\n                            \n                                Humor\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/horror_31/index.html">\n                            \n                                Horror\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/history_32/index.html">\n                            \n                                History\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/food-and-drink_33/index.html">\n                            \n                                Food and Drink\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian-fiction_34/index.html">\n                            \n                                Christian Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/business_35/index.html">\n                            \n                                Business\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/biography_36/index.html">\n                            \n                                Biography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/thriller_37/index.html">\n                            \n                                Thriller\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/contemporary_38/index.html">\n                            \n                                Contemporary\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/spirituality_39/index.html">\n                            \n                                Spirituality\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/academic_40/index.html">\n                            \n                                Academic\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/self-help_41/index.html">\n                            \n                                Self Help\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical_42/index.html">\n                            \n                                Historical\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian_43/index.html">\n                            \n                                Christian\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/suspense_44/index.html">\n                            \n                                Suspense\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/short-stories_45/index.html">\n                            \n                                Short Stories\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/novels_46/index.html">\n                            \n                                Novels\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/health_47/index.html">\n                            \n                                Health\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/politics_48/index.html">\n                            \n                                Politics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/cultural_49/index.html">\n                            \n                                Cultural\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/erotica_50/index.html">\n                            \n                                Erotica\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/crime_51/index.html">\n                            \n                                Crime\n                            \n                        </a>\n\n                        </li>\n                        \n                            </ul></li>\n                        \n                \n            </ul>\n        </div>\n    \n    \n\n            </aside>\n\n            <div class="col-sm-8 col-md-9">\n                \n                <div class="page-header action">\n                    <h1>All products</h1>\n                </div>\n                \n\n                \n\n\n\n<div id="messages">\n\n</div>\n\n\n                <div id="promotions">\n                    \n                </div>\n\n                \n    <form method="get" class="form-horizontal">\n        \n        <div style="display:none">\n            \n            \n        </div>\n\n        \n            \n                \n                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.\n                \n            \n            \n        \n    </form>\n    \n        <section>\n            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>\n\n            <div>\n                <ol class="row">\n                    \n              

Ответ содержит HTML-код страницы, к которой мы обратились.

## Beautiful Soup

Как же нам теперь достать из HTML-разметки нужное? Нам поможет красивый суп!

Beautiful Soup — это библиотека для извлечения данных из HTML и XML. С ее помощью можно извлечь из сложной структуры разметки нужную информацию.

Документация: https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [ ]:
from bs4 import BeautifulSoup

Создаем объект, через методы которого будем искать нужные теги и извлекать их содержимое

In [ ]:
soup = BeautifulSoup(res.text)
soup

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]--><!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]--><!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]--><!--[if gt IE 8]><!--><html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    All products | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="index.html">Home</a>
</li>
<li class="active">All products</li>
</ul>
<div class="row">
<aside class="sidebar col-sm-4 col-md-3">
<div id="promotions_left">
</div>
<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="catalogue/category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>
</aside>
<div class="col-sm-8 col-md-9">
<div class="page-header action">
<h1>All products</h1>
</div>
<div id="messages">
</div>
<div id="promotions">
</div>
<form class="form-horizontal" method="get">
<div style="display:none">
</div>
<strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>
<section>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
<div>
<ol class="row">
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">Â£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">Â£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">Â£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">Â£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">Â£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">Â£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">Â£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">Â£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">Â£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">

Метод `find_all` позволяет найти все указанные теги с нужными атрибутами (с вложениями), возвращает список

In [ ]:
books = soup.find_all('article', class_='product_pod')
print(len(books))
print(books[0])

20
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

Напишем функцию, которая будет собирать датафрейм на основе книг с главной страницы сайта.

In [ ]:
import pandas as pd

def get_books():
    url = 'https://books.toscrape.com/'
    response = requests.get(url)
    soup = BeautifulSoup(response.text)

    books = soup.find_all('article', 'product_pod')

    rows = []

    for book in books:
        title = book.find('h3').find('a').get('title')
        # print(title)
        price = book.find('p', 'price_color').text[1:]
        # print(price)
        rating = book.find('p', 'star-rating').get('class')[1]
        # print(rating)

        rows.append({'title': title, 'price': price, 'rating': rating})


    res = pd.DataFrame(rows)
    return res

get_books()
get_books().to_csv('books.csv', index=False)

Модифицируем функцию, чтобы могли собирать информацию с нескольких страниц.

При этом стоит включить небольшую задержку между запросами, чтобы не перегружать сервер и не вызывать блокировку.

In [ ]:
import time

def get_books(pages=1):
    base_url = 'https://books.toscrape.com/catalogue/'

    rows = []

    for page in range(1, pages+1):
        response = requests.get(f'{base_url}page-{page}.html')
        time.sleep(0.2)
        soup = BeautifulSoup(response.text)

        books = soup.find_all('article', 'product_pod')



        for book in books:
            title = book.find('h3').find('a').get('title')
            price = book.find('p', 'price_color').text[1:]
            rating = book.find('p', 'star-rating').get('class')[1]

            rows.append({'title': title, 'price': price, 'rating': rating})


    res = pd.DataFrame(rows)
    return res

get_books(3)

                                                title   price rating
0                                A Light in the Attic  £51.77  Three
1                                  Tipping the Velvet  £53.74    One
2                                          Soumission  £50.10    One
3                                       Sharp Objects  £47.82   Four
4               Sapiens: A Brief History of Humankind  £54.23   Five
5                                     The Requiem Red  £22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  £33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  £17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  £22.60   Four
9                                     The Black Maria  £52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    Two
11                              Shakespeare's Sonnets  £20.66   Four
12                                        Set Me Free  £17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29   Five
14                          Rip it Up and Start Again  £35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  £57.25  Three
16                                               Olio  £23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    One
18                       Libertarianism for Beginners  £51.33    Two
19                            It's Only the Himalayas  £45.17    Two
20                                        In Her Wake  £12.84    One
21                                    How Music Works  £37.32    Two
22  Foolproof Preserving: A Guide to Small Batch J...  £30.52  Three
23                         Chase Me (Paris Nights #2)  £25.27   Five
24                                         Black Dust  £34.53   Five
25                      Birdsong: A Story in Pictures  £54.64  Three
26  America's Cradle of Quarterbacks: Western Penn...  £22.50  Three
27                     Aladdin and His Wonderful Lamp  £53.13  Three
28  Worlds Elsewhere: Journeys Around Shakespeareâ...  £40.30   Five
29                                     Wall and Piece  £44.18   Four
30  The Four Agreements: A Practical Guide to Pers...  £17.66   Five
31  The Five Love Languages: How to Express Heartf...  £31.05  Three
32                                  The Elephant Tree  £23.82   Five
33                             The Bear and the Piano  £36.89    One
34                                     Sophie's World  £15.94   Five
35                                        Penny Maybe  £33.29  Three
36     Maude (1883-1993):She Grew Up with the country  £18.02    Two
37                               In a Dark, Dark Wood  £19.63    One
38                                Behind Closed Doors  £52.22   Four
39                     You can't bury them all: Poems  £33.63    Two
40                     Slow States of Collapse: Poems  £57.31  Three
41                              Reasons to Stay Alive  £26.41    Two
42                        Private Paris (Private #10)  £47.61   Five
43  #HigherSelfie: Wake Up Your Life. Free Your So...  £23.11   Five
44                    Without Borders (Wanderlove #1)  £45.07    Two
45                                   When We Collided  £31.77    One
46                       We Love You, Charlie Freeman  £50.27   Five
47            Untitled Collection: Sabbath Poems 2014  £14.27   Four
48  Unseen City: The Majesty of Pigeons, the Discr...  £44.18   Four
49                                     Unicorn Tracks  £18.78  Three
50  Unbound: How Eight Technologies Made Us Human,...  £25.52    One
51  Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRo...  £16.28    One
52  Throwing Rocks at the Google Bus: How Growth B...  £31.12  Three
53                                    This One Summer  £19.49   Four
54                                             Thirst  £17.27   Five
55        The Torch Is Passed: A Harding Family Story  £19.09    One
56                    The Secret of Dreadwillow Carse  £56.13    One
57  The Pioneer Woman Cooks: Dinnertime: Comfort C...  £56.41    One
58                                The Past Never Ends  £56.50   Four
59  The Natural History of Us (The Fine Art of Pre...  £45.22  Three

Теперь соберем описание книг.

In [ ]:
def get_books(pages=1):
    base_url = 'https://books.toscrape.com/catalogue/'

    rows = []

    for page in range(1, pages+1):
        response = requests.get(f'{base_url}page-{page}.html')
        time.sleep(0.2)
        soup = BeautifulSoup(response.text)

        books = soup.find_all('article', 'product_pod')

        for book in books:
            title = book.find('h3').find('a').get('title')
            price = book.find('p', 'price_color').text[1:]
            rating = book.find('p', 'star-rating').get('class')[1]


            book_link = base_url + book.find('h3').find('a').get('href')
            book_info = requests.get(book_link)
            book_info.encoding = 'utf-8'  # исправляем проблему с кодировкой
            time.sleep(0.2)

            soup_info = BeautifulSoup(book_info.text)

            # найдем тег p после div с id product_description
            description = soup_info.find('div', id='product_description').find_next('p').text
            rows.append({'title': title, 'price': price, 'rating': rating, 'description': description})


    res = pd.DataFrame(rows)
    return res

get_books()

,title,price,rating,description
0,A Light in the Attic,£51.77,Three,It's hard to imagine a world without A Light i...
1,Tipping the Velvet,£53.74,One,"""Erotic and absorbing...Written with starling ..."
2,Soumission,£50.10,One,"Dans une France assez proche de la nôtre, un h..."
3,Sharp Objects,£47.82,Four,"WICKED above her hipbone, GIRL across her hear..."
4,Sapiens: A Brief History of Humankind,£54.23,Five,From a renowned historian comes a groundbreaki...
5,The Requiem Red,£22.65,One,Patient Twenty-nine.A monster roams the halls ...
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,Four,Drawing on his extensive experience evaluating...
7,The Coming Woman: A Novel Based on the Life of...,£17.93,Three,"""If you have a heart, if you have a soul, Kare..."
8,The Boys in the Boat: Nine Americans and Their...,£22.60,Four,For readers of Laura Hillenbrand's Seabiscuit ...
9,The Black Maria,£52.15,One,"Praise for Aracelis Girmay:""[Girmay's] every l..."
10,"Starving Hearts (Triangular Trade Trilogy, #1)",£13.99,Two,"Since her assault, Miss Annette Chetwynd has b..."
11,Shakespeare's Sonnets,£20.66,Four,This book is an important and complete collect...
12,Set Me Free,£17.46,Five,Aaron Ledbetter’s future had been planned out ...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,£52.29,Five,Scott Pilgrim's life is totally sweet. He's 23...
14,Rip it Up and Start Again,£35.02,Five,"Punk's raw power rejuvenated rock, but by the ..."
15,Our Band Could Be Your Life: Scenes from the A...,£57.25,Three,This is the never-before-told story of the mus...
16,Olio,£23.88,One,"Part fact, part fiction, Tyehimba Jess's much ..."
17,Mesaerion: The Best Science Fiction Stories 18...,£37.59,One,"Andrew Barger, award-winning author and engine..."
18,Libertarianism for Beginners,£51.33,Two,Libertarianism isn't about winning elections; ...
19,It's Only the Himalayas,£45.17,Two,"“Wherever you go, whatever you do, just . . . ..."

Напишем скрипт, который будет собирать новости с сайта Коммерсанта

In [ ]:
url = 'https://www.kommersant.ru/search/results?search_query=python'
res = requests.get(url)
res.text

'\r\n<!DOCTYPE html>\r\n\r\n<html class="no-js"  lang="ru">\r\n<head>\r\n    <title>Коммерсантъ: последние новости России и мира</title>\r\n    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />\r\n    <meta charset="utf-8" />\r\n\r\n    <meta name="format-detection" content="telephone=no" />\r\n    <meta name="title" content="Коммерсантъ: последние новости России и мира" />\r\n    <meta name="description" content="Актуальные новости, объективный анализ и эксклюзивные комментарии о важнейших событиях и трендах" />\r\n    <meta name="keywords" content="Новости,Политика,Экономика,Бизнес,Финансы,Дело,Биржа,Рынок,Акции,Прогнозы,Критика,Интервью,Рейтинги,Документы,Деньги,Власть,Автопилот,Тематические страницы,Первые лица,Деловые новости,Мировая практика,Культура,Спорт,Weekend,Астрологический прогноз,Погода мира,Курсы валют ЦБ РФ" />\r\n\r\n    <meta name="yandex-verification" content="50df68945a519dbd" />\r\n\r\n    \r\n<meta name="viewport" content="width=device-width, initial-scale=1.0" />\r\n\r\n\r\n\r\n        <meta property="fb:app_id" content="324580610921010" />\r\n        <meta property="og:type" content="website" />\r\n        <meta property="og:site_name" content="Коммерсантъ" />\r\n        <meta property="og:url" content="https://www.kommersant.ru" />\r\n        <meta property="og:title" content="Коммерсантъ: последние новости России и мира" />\r\n        <meta property="og:description" content="Актуальные новости, объективный анализ и эксклюзивные комментарии о важнейших событиях и трендах" />\r\n        <meta property="og:image" content="https://iy.kommersant.ru/ContentFlex/images/logo.png" />\r\n        <link rel="image_src" href="https://iy.kommersant.ru/CorpPics/logo200.jpg" />\r\n\r\n    \r\n<!-- common css -->\r\n    <script>\r\n        document.documentElement.classList.remove(\'no-js\');\r\n    </script>\r\n\r\n    \r\n    <link rel="preload" as="style" href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650">\r\n    <link rel="stylesheet" media="print" onload="this.onload=null;this.removeAttribute(\'media\');" href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650">\r\n    <noscript>\r\n        <link rel="stylesheet" href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650">\r\n    </noscript>\r\n\r\n    <link href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonCss.css?2409301708092569" rel="stylesheet">\r\n    <link rel="preload" href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonDeferCss.css?2409301708092570" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">\r\n    <noscript><link rel="stylesheet" href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonDeferCss.css?2409301708092570"></noscript>\r\n<!-- common css end -->\r\n\r\n\r\n    \r\n\r\n    \r\n<link rel="apple-touch-icon" sizes="57x57" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-57.png">\r\n<link rel="apple-touch-icon" sizes="60x60" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-60.png">\r\n<link rel="apple-touch-icon" sizes="72x72" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-72.png">\r\n<link rel="apple-touch-icon" sizes="76x76" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-76.png">\r\n<link rel="apple-touch-icon" sizes="114x114" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-114.png">\r\n<link rel="apple-touch-icon" sizes="120x120" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-120.png">\r\n<link rel="apple-touch-icon" sizes="144x144" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-144.png">\r\n<link rel="apple-touch-icon" sizes="152x152" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-152.png">\r\n<link rel="apple-touch-icon" sizes="180x180" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-180.png">\r\n<link rel="icon" type="image/svg+xml" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon.svg">\r\n<link rel="icon" type="image/png" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon-32.png" sizes="32x32">\r\n<link rel="icon" type="image/png" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/android-chrome-192.png" sizes="192x192">\r\n<link rel="icon" type="image/png" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon-16.png" sizes="16x16">\r\n<link rel="manifest" href="/manifest.json">\r\n<link rel="mask-icon" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/safari-pinned-tab.svg" color="#5bbad5">\r\n<meta name="msapplication-TileColor" content="#2d89ef">\r\n<meta name="msapplication-TileImage" content="https://iy.kommersant.ru/ContentFlex/images/favicons2020/mstile-144x144.png">\r\n<meta name="theme-color" content="#ffffff">\r\n\r\n    \r\n    <!-- search page head css -->\r\n    <link rel="stylesheet" href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.search.css?2409301708092660" />\r\n    <!-- search page head css end -->\r\n\r\n    \r\n    <script>\r\n                window.puids = {\r\n                    \'puid1\': \'0\',\r\n                    \'puid2\': \'\',\r\n                    \'puid3\': \'\',\r\n                    \'puid4\': \'i0\',\r\n                    \'puid5\': \'999\'\r\n                };\r\n    </script>\r\n\r\n\r\n    \r\n\r\n<!-- common scripts -->\r\n<link rel="preconnect" href="https://iy.kommersant.ru">\r\n    <script src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.pushPopup.js?2409301708092657" async></script>\r\n<script src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonJS.js?2409301708092570"></script>\r\n<script src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.pollJS.js?2409301708092651" defer></script>\r\n\r\n<script>\r\n    kommersant.antiCache.jsMark = \'https://iy.kommersant.ru/ContentFlex/js/jquery.mark.min.js?2109231134459908\';\r\n    kommersant.antiCache.jsJqueryValidate = \'https://iy.kommersant.ru/ContentFlex/js/jquery.validate.min.js?2109231134459908\';\r\n    kommersant.antiCache.jsNanoScroller = \'https://iy.kommersant.ru/ContentFlex/js/jquery.nanoscroller.min.js?2109231134459908\';\r\n    kommersant.antiCache.jsScrollMagic = \'https://iy.kommersant.ru/ContentFlex/js/scrollmagic/ScrollMagic.min.js?2109231134459908\';\r\n    kommersant.antiCache.jsHighmapsCisDisputed = \'https://iy.kommersant.ru/ContentFlex/js/highmaps/cis-disputed.js?2109231134459908\';\r\n    kommersant.antiCache.jsCharts = \'https://iy.kommersant.ru/ContentFlex/js/charts.new2021.js?2202141653190991\';\r\n    kommersant.antiCache.jsWidgets = \'https://iy.kommersant.ru/ContentFlex/js/widgets.new2021.js?2409161717291205\';\r\n    kommersant.antiCache.jsHighmapsWorldDisputed = \'https://iy.kommersant.ru/ContentFlex/js/highmaps/world-disputed.js?2109231134459908\';\r\n</script>\r\n\r\n\r\n\r\n<script>\r\n    window.__storage__ = window.__storage__ || {}\r\n    window.__storage__.lentaBanners = {\r\n        businessAnnounce: " &lt;!--197--&gt; &lt;!--AdFox START--&gt; &lt;!--kommersant--&gt; &lt;!--Площадка: Kommersant_redesign / 0Десктоп / 3й анонс в ленте--&gt; &lt;!--Категория: &lt;не задана&gt;--&gt; &lt;!--Тип баннера: 3й анонс в ленте--&gt; &lt;!--197--&gt;  &lt;div id=&quot;adfox_162799247887971226&quot;&gt;&lt;/div&gt; &lt;script&gt;   window.kommersant.adv(   () =&gt; {     window.yaContextCb.push(() =&gt; {         Ya.adfoxCode.create(         {             ownerId: 1092,             containerId: &#39;adfox_162799247887971226&#39;,             params: Object.assign({ p1: &#39;cqgxq&#39;, p2: &#39;hhrr&#39; }, window.puids || {})         },         [&#39;desktop&#39;,&#39;phone&#39;,&#39;tablet&#39;],         {             tabletWidth: 1197.99,             phoneWidth: 1197.99,             isAutoReloads: false         });     });   },   () =&gt; {}); &lt;/script&gt; ",\r\n        twoAnnounces: [{"Id":2602,"ProfileId":1,"Position":1,"Type":1,"DocId":7180467,"Title":"Для тех, кто понимает в настоящей роскоши","Subtitle":"","Link":null,"IsSelfLink":false,"ImageSrc":null,"Enabled":true,"Category":"Промо","AdvDescription":null},{"Id":2652,"ProfileId":1,"Position":2,"Type":1,"DocId":7196629,"Title":"Кто владеет аудиторией, тот повелевает рынком","Subtitle":"Участники рекламной отрасли обсудили эволюцию стратегий в обществе постпотребления.","Link":null,"IsSelfLink":false,"ImageSrc":null,"Enabled":true,"Category":"Промо","AdvDescription":null}]\r\n    }\r\n</script>\r\n<script src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.lentaVue.js?2409301708092629" async></script>\r\n\r\n<script>\r\n    window.kommersant.regionId = 77;\r\n</script>\r\n<!-- common scripts end-->\r\n\r\n\r\n<!--200-->\r\n<script>window.yaContextCb = window.yaContextCb || []</script>\r\n<script src="https://yandex.ru/ads/system/context.js" async></script>\r\n\r\n<!--204-->\r\n\r\n\r\n\r\n\r\n    \r\n    \r\n    <script>\r\n        window.kommersant.backend.adv = {\r\n            180: \'\\r\\n\\u003c!--180--\\u003e\\r\\n\\r\\n\\u003c!--AdFox START--\\u003e\\r\\n\\u003c!--kommersant--\\u003e\\r\\n\\u003c!--Площадка: Kommersant_redesign / 0Десктоп / БА2--\\u003e\\r\\n\\u003c!--Категория: \\u003cне задана\\u003e--\\u003e\\r\\n\\u003c!--Тип баннера: СБА_БА--\\u003e\\r\\n\\u003c!--180--\\u003e\\r\\n\\u003cdiv id=\\"adfox_161707797679975629\\"\\u003e\\u003c/div\\u003e\\r\\n\\u003cscript\\u003e\\r\\nwindow.kommersant.adv(\\r\\n  () =\\u003e {\\r\\n    window.yaContextCb.push(() =\\u003e {\\r\\n    Ya.adfoxCode.createScroll({\\r\\n        ownerId: 1092,\\r\\n        containerId: \\u0027adfox_161707797679975629\\u0027,\\r\\n        params: Object.assign(\\r\\n            {\\r\\n                p1: \\u0027corsv\\u0027,\\r\\n                p2: \\u0027hedx\\u0027,\\r\\n            }, window.puids || {}\\r\\n        ),\\r\\n    }, [\\u0027desktop\\u0027], {\\r\\n        tabletWidth: 1197.99,\\r\\n        phoneWidth: 1197.99,\\r\\n        isAutoReloads: false\\r\\n    })\\r\\n});\\r\\n  },\\r\\n  () =\\u003e {\\r\\n    /* AdFox for members */\\r\\n  }\\r\\n);\\r\\n\\r\\n\\u003c/script\\u003e\',\r\n        };\r\n    </script>\r\n\r\n</head>\r\n<body>\r\n    \r\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position: absolute; width: 0; height: 0" aria-hidden="true"><symbol id="vicon-burger" viewBox="0 0 30 30"><path d="M25 6v4H5V6h20zM5 17h20v-4H5v4zm0 7h20v-4H5v4z"/></symbol><symbol id="vicon-fm" viewBox="0 0 30 30"><path d="M24.25 16.21 20 18.34v-6.68l4.25 2.13c1 .5 1 1.92 0 2.42zm-9.7-4.96 1.2 4.56 1.18-4.56h2.24l-12.2-6.1C6.05 4.68 5 5.34 5 6.34v4.9h5.8v1.61H7.34v1.31h2.94v1.52H7.35v3.06H5v4.9c0 1 1.06 1.66 1.96 1.2l12.21-6.1H18.1v-5.72l-1.49 5.72h-1.73l-1.48-5.72v5.72h-1.92v-7.5h3.08z"/></symbol><symbol id="vicon-main_logo" viewBox="0 0 158 20"><path d="M40 4h5v12h-4V9l-2.8 7h-1.9c-.2-.7-.5-.6-2.3-7v7h-4V4h5.5l1.8 6.6L40 4zm13.3 6.6L51.5 4H46v12h4V9c1.8 6.4 2 6.3 2.3 7h2c0-.3 2.6-6.6 2.7-7v7h4V4h-5l-2.7 6.6zM15.7 0H10L5 5.6V0H0v16h5v-5.1l1.5-1.6 4 6.7h6L9.8 6l5.8-6zM29 10c0 4-2.5 6.3-6.6 6.3-4 0-6.5-2.3-6.5-6 0-3.9 2.4-6.2 6.5-6.2 4 0 6.6 2.4 6.6 6zm-4.3 0c0-1.8-1-3.1-2.2-3.1-1.7 0-2.3 1.6-2.3 3.2 0 3 1.4 3.4 2.2 3.4 1 0 2.3-.6 2.3-3.4zM158 12c0 3-2.7 4-5 4h-7V7h-3V4h7v4h3c3.5 0 5 2.1 5 4zm-4 0c0-1.2-1.1-1.4-2.1-1.4h-1.7v2.7h1.7c1 0 2.1-.1 2.1-1.3zm-24-5h4v9h4V7h4V4h-12v3zm-14 7.5c0 .6 0 1 .6 1.5h-4.7l-.2-1.5-.3.2a5.8 5.8 0 0 1-4.3 1.6c-2 0-4-.9-4-3.4 0-3.1 3-3.5 5.3-3.8 1.7-.2 3-.3 3-1.4 0-.7-.6-1.2-1.7-1.2-1 0-1.6.4-1.8 1.2h-4.2c.2-2.4 2.2-3.6 6.3-3.6 5.4 0 6 2 6 4.8v5.6zm-4.5-4-.3.2a7 7 0 0 1-1.6.5c-1.1.2-2.1.4-2.1 1.6 0 .7.7 1.2 1.7 1.2 2 0 2.3-1.6 2.3-3.1v-.3zM125 9h-4V4h-4v12h4v-4h4v4h4V4h-4v5zm-36 1.1c0 4.6-2.4 5.9-5 5.9a5 5 0 0 1-2-.5c-.3-.2-1-.5-1.6-1.1L80 14v6h-4V4h4v2c.6-1.4 2.6-1.9 3.9-1.9 3.7 0 5 3.2 5 6zm-4.3 0c0-1.8-.9-3-2.3-3-1.3 0-2.1 1.3-2.1 3 0 1.8.8 3 2.1 3 1.4 0 2.3-1.2 2.3-3zm-18.4.9v.3c0 1.4 1.1 2.5 2.6 2.5a2 2 0 0 0 1.7-.8h4.2c-1.2 3-4.7 3.3-6.2 3.3-4 0-6.6-2.4-6.6-6s2.7-6.2 6.5-6.2c4.2 0 6.8 2.6 6.8 6.9h-9zm0-2H71c0-1.3-1-2.3-2.3-2.3-1.5 0-2.4.9-2.4 2.3zM96 13.6c-1.4 0-2.3-1.1-2.3-3.2C93.7 7.5 95 7 96 7c1 0 1.8.7 2 1.7h4.3C101.9 5.8 99.6 4 96 4c-4 0-6.6 2.4-6.6 6.2 0 3.6 2.6 6 6.6 6 2.1 0 5.6-.6 6.3-4.3H98c-.3 1-1 1.5-2 1.5z"/></symbol><symbol id="vicon-rarrow" viewBox="0 0 30 30"><path d="M9.22.33c.85-.59 2.02-.38 2.61.47l9.38 13.48c.45.66.44 1.54-.03 2.18l-9.37 12.77a1.87 1.87 0 1 1-3.03-2.22L17.36 15 8.76 2.94a1.88 1.88 0 0 1 .46-2.6z"/></symbol><symbol id="vicon-regions" viewBox="0 0 30 30"><path d="M15.1 5C19 5 22 8 22 11.9c0 4.3-6.9 13.1-6.9 13.1s-6.8-8.7-6.8-13.1C8.3 8 11.3 5 15 5zm0 10a3.1 3.1 0 1 0 0-6.2 3.1 3.1 0 0 0 0 6.2z"/></symbol><symbol id="vicon-search" viewBox="0 0 30 30"><path d="m24.55 22.97-5-5.01a8.09 8.09 0 1 0-1.58 1.58l5 5.02c.53.52 1.3.6 1.74.15s.37-1.21-.16-1.74zM13.1 18.68a5.6 5.6 0 1 1 0-11.2 5.6 5.6 0 0 1 0 11.2z"/></symbol></svg>\r\n\r\n    \r\n<div style="position: absolute; visibility: hidden" id="counters-top">\r\n<script>\r\n(function () {\r\n  window.kommersantAnalytics = {\r\n    adblock: \'\',\r\n    audio: \'No\',\r\n    authors: \'\',\r\n    date: \'\',\r\n    liveinternet: \'kommersant\',\r\n    mainpage: \'Поиск\',\r\n    paid: \'No\',\r\n    photo: \'No\',\r\n    publishing: \'\',\r\n    region: \'\',\r\n    rubrics: \'\',\r\n    themegroups: \'\',\r\n    themes: \'\',\r\n    department:\'none\',\r\n    userId: String(window.kommersant?.user.data.UserId || \'none\'),\r\n    userType: \'none\',\r\n  };\r\n  var advad = new Image();\r\n  advad.onload = function () {\r\n    window.kommersantAnalytics.adblock = \'No\';\r\n  };\r\n  advad.onerror = function () {\r\n    window.kommersantAnalytics.adblock = \'Yes\';\r\n  };\r\n  advad.src = \'https://iy.kommersant.ru/ContentFlex/images/adv.gif\';\r\n})();\r\n</script>\r\n\r\n<!-- Kommersant -->\r\n<script>\r\nfunction counterKommersant() {\r\n//new Image().src = \'//www.kommersant.ru/headerfooter/counterA?p=0&ref=\' + escape(document.referrer) + \'&rnd=\' + Math.floor(Math.random() * 1000000000);\r\n}\r\nfunction counterKommersantRead() {\r\n\r\n}\r\ncounterKommersant();\r\ncounterKommersantRead();\r\n</script>\r\n<noscript>\r\n\r\n</noscript>\r\n<!-- /Kommersant -->\r\n\r\n<!-- Rating@Mail.ru counter -->\r\n<script type="text/javascript">\r\nvar _tmr = window._tmr || (window._tmr = []);\r\n_tmr.push({id: "84394", type: "pageView", start: (new Date()).getTime()});\r\n(function (d, w, id) {\r\nif (d.getElementById(id)) return;\r\nvar ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;\r\nts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";\r\nvar f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};\r\nif (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }\r\n})(document, window, "topmailru-code");\r\n</script><noscript><div>\r\n<img src="//top-fwz1.mail.ru/counter?id=84394;js=na" style="border:0;position:absolute;left:-9999px;" alt="" />\r\n</div></noscript>\r\n<!-- //Rating@Mail.ru counter -->\r\n\r\n\r\n<!--LiveInternet counter-->\r\n<script>\r\nfunction counterLiveInternet() {\r\n  new Image().src = "//counter.yadro.ru/hit" + (window.kommersantAnalytics.liveinternet ? ";" + window.kommersantAnalytics.liveinternet : "") + "?r" + escape(document.referrer) + ((typeof (screen) == "undefined") ? "" : ";s" + screen.width + "*" + screen.height + "*" + (screen.colorDepth ? screen.colorDepth : screen.pixelDepth)) + ";u" + escape(document.URL) + ";h" + escape(document.title.substring(0, 80)) + ";" + Math.random();\r\n}\r\ncounterLiveInternet();\r\n</script>\r\n<noscript>\r\n<img src="//counter.yadro.ru/hit;kommersant" width="1" height="1" alt="">\r\n</noscript>\r\n<!--/LiveInternet-->\r\n\r\n<!-- Yandex.Metrika counter -->\r\n<script type="text/javascript">\r\n  var yaParams = {\r\n  \r\n      department: \'none\',\r\n  \r\n};\r\n</script>\r\n<script type="text/javascript" >\r\n  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};\r\n  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})\r\n  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");\r\n\r\n  ym(153166, "init", {\r\n    clickmap:true,\r\n    trackLinks:true,\r\n    accurateTrackBounce:true,\r\n    trackHash:true,\r\n    params: yaParams\r\n  });\r\n\r\n  window.kommersant?.user.ready.then(() => {\r\n    if (window.kommersant.user.data.UserId) {\r\n      ym(153166, \'setUserID\', window.kommersant.user.data.UserId);\r\n      ym(153166, \'params\', { \'UserID\': window.kommersant.user.data.UserId });\r\n    }\r\n  });\r\n</script>\r\n<noscript><div><img src="https://mc.yandex.ru/watch/153166" style="position:absolute; left:-9999px;" alt="" /></div></noscript>\r\n<!-- /Yandex.Metrika counter -->\r\n\r\n<img id="advad" src="https://iy.kommersant.ru/ContentFlex/images/adv.gif" style="display: none" />\r\n\r\n<!-- Google tag (gtag.js) -->\r\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-TKM0FJ12D1"></script>\r\n<script>\r\n  window.dataLayer = window.dataLayer || [];\r\n  function gtag() {\r\n    dataLayer.push(arguments);\r\n  }\r\n  gtag(\'js\', new Date());\r\n  gtag(\'config\', \'G-TKM0FJ12D1\', window.kommersant?.utils.getAnalyticsObjectGtag() || {});\r\n\r\n  window.kommersant?.user.ready.then(() => {\r\n    if(window.kommersant.user.data.UserId) {\r\n      gtag(\'config\', \'G-TKM0FJ12D1\',{ user_id: window.kommersant.user.data.UserId });\r\n      gtag(\'set\', { user_id: window.kommersant.user.data.UserId });\r\n    }\r\n  });\r\n</script>\r\n\r\n\r\n<!-- tns-counter.ru -->\r\n<script>\r\nfunction counterTnsNew() {\r\n  const matchesLkuid = document.cookie.match(/(?<!\\w)lkuid=([^;]*)/);\r\n  const lkuid = matchesLkuid ? matchesLkuid[1] : \'\';\r\n  const matchesSessionId = document.cookie.match(/(?<!\\w)kommersantSessionId=([^;]*)/);\r\n  let sessionId;\r\n  if (matchesSessionId) {\r\n    sessionId = matchesSessionId[1];\r\n  } else {\r\n    const size = 16;\r\n    let seed = \'\';\r\n    sessionId = \'\';\r\n    for (let i = 48; i <= 122; i += (i === 57 ? 40 : 1)) {\r\n      seed += String.fromCharCode(i);\r\n    }\r\n    for (let i = 0; i < size; i += 1) {\r\n      sessionId += seed.charAt(Math.floor(Math.random() * seed.length));\r\n    }\r\n    document.cookie = \'kommersantSessionId=\' + sessionId;\r\n  }\r\n  const idlc = window.doc && window.doc.id || null;\r\n  const ver = 0;\r\n  const type = (window.doc && window.doc.id) ? 4 : 0;\r\n  let url = \'//tns-counter.ru/e/ec01\';\r\n  url += \'&cid=kommersant_ru\';\r\n  url += \'&typ=1\';\r\n  url += \'&tms=kommersant_ru\';\r\n  url += \'&idc=155\';\r\n  url += \'&uid=\' + sessionId;\r\n  url += \'&hid=\' + lkuid;\r\n  url += idlc ? \'&idlc=\' + idlc : \'\';\r\n  url += \'&ver=\' + ver;\r\n  url += \'&type=\' + type;\r\n  fetch(url, { credentials: \'include\' }).catch(() => false);\r\n}\r\ncounterTnsNew();\r\n</script>\r\n<noscript>\r\n<img src="//tns-counter.ru/e/ec01&cid=kommersant_ru&typ=1&tms=kommersant_ru&idc=155&ver=0&type=0" width="1" height="1" alt="">\r\n</noscript>\r\n<!--/tns-counter.ru -->\r\n\r\n\r\n<!-- tns-counter.ru -->\r\n<script>\r\nfunction counterTnsOld() {\r\n  new Image().src = \'//tns-counter.ru/V13a***R>\' + document.referrer.replace(/\\*/g, \'%2a\') + \'*kommersant_ru/ru/CP1251/tmsec=komm_junk/\' + Math.floor(Math.random() * 900000000 + 100000000);\r\n}\r\ncounterTnsOld();\r\n</script>\r\n<noscript>\r\n<img src="//tns-counter.ru/V13a****kommersant_ru/ru/CP1251/tmsec=komm_junk/" width="1" height="1" alt="">\r\n</noscript>\r\n<

Параметры, особенно если их много, удобно передавать в качестве словаря

In [ ]:
url = 'https://www.kommersant.ru/search/results'
params = {
    'search_query': 'python'
}
res = requests.get(url, params)
soup = BeautifulSoup(res.text)
soup

<!DOCTYPE html>
<html class="no-js" lang="ru">
<head>
<title>Коммерсантъ: последние новости России и мира</title>
<meta content="IE=edge, chrome=1" http-equiv="X-UA-Compatible"/>
<meta charset="utf-8"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="Коммерсантъ: последние новости России и мира" name="title"/>
<meta content="Актуальные новости, объективный анализ и эксклюзивные комментарии о важнейших событиях и трендах" name="description"/>
<meta content="Новости,Политика,Экономика,Бизнес,Финансы,Дело,Биржа,Рынок,Акции,Прогнозы,Критика,Интервью,Рейтинги,Документы,Деньги,Власть,Автопилот,Тематические страницы,Первые лица,Деловые новости,Мировая практика,Культура,Спорт,Weekend,Астрологический прогноз,Погода мира,Курсы валют ЦБ РФ" name="keywords"/>
<meta content="50df68945a519dbd" name="yandex-verification"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="324580610921010" property="fb:app_id"/>
<meta content="website" property="og:type"/>
<meta content="Коммерсантъ" property="og:site_name"/>
<meta content="https://www.kommersant.ru" property="og:url"/>
<meta content="Коммерсантъ: последние новости России и мира" property="og:title"/>
<meta content="Актуальные новости, объективный анализ и эксклюзивные комментарии о важнейших событиях и трендах" property="og:description"/>
<meta content="https://iy.kommersant.ru/ContentFlex/images/logo.png" property="og:image"/>
<link href="https://iy.kommersant.ru/CorpPics/logo200.jpg" rel="image_src"/>
<!-- common css -->
<script>
        document.documentElement.classList.remove('no-js');
    </script>
<link as="style" href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650" rel="preload"/>
<link href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650" media="print" onload="this.onload=null;this.removeAttribute('media');" rel="stylesheet"/>
<noscript>
<link href="https://iy.kommersant.ru/ContentFlex/ajax/fonts/noto-sans/noto-sans.css?2404271704552650" rel="stylesheet"/>
</noscript>
<link href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonCss.css?2409301708092569" rel="stylesheet"/>
<link as="style" href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonDeferCss.css?2409301708092570" onload="this.onload=null;this.rel='stylesheet'" rel="preload"/>
<noscript><link href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonDeferCss.css?2409301708092570" rel="stylesheet"/></noscript>
<!-- common css end -->
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/apple-touch-icon-180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon.svg" rel="icon" type="image/svg+xml"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon-32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/android-chrome-192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/favicon-16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/manifest.json" rel="manifest"/>
<link color="#5bbad5" href="https://iy.kommersant.ru/ContentFlex/images/favicons2020/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#2d89ef" name="msapplication-TileColor"/>
<meta content="https://iy.kommersant.ru/ContentFlex/images/favicons2020/mstile-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- search page head css -->
<link href="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.search.css?2409301708092660" rel="stylesheet"/>
<!-- search page head css end -->
<script>
                window.puids = {
                    'puid1': '0',
                    'puid2': '',
                    'puid3': '',
                    'puid4': 'i0',
                    'puid5': '999'
                };
    </script>
<!-- common scripts -->
<link href="https://iy.kommersant.ru" rel="preconnect"/>
<script async="" src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.pushPopup.js?2409301708092657"></script>
<script src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.commonJS.js?2409301708092570"></script>
<script defer="" src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.pollJS.js?2409301708092651"></script>
<script>
    kommersant.antiCache.jsMark = 'https://iy.kommersant.ru/ContentFlex/js/jquery.mark.min.js?2109231134459908';
    kommersant.antiCache.jsJqueryValidate = 'https://iy.kommersant.ru/ContentFlex/js/jquery.validate.min.js?2109231134459908';
    kommersant.antiCache.jsNanoScroller = 'https://iy.kommersant.ru/ContentFlex/js/jquery.nanoscroller.min.js?2109231134459908';
    kommersant.antiCache.jsScrollMagic = 'https://iy.kommersant.ru/ContentFlex/js/scrollmagic/ScrollMagic.min.js?2109231134459908';
    kommersant.antiCache.jsHighmapsCisDisputed = 'https://iy.kommersant.ru/ContentFlex/js/highmaps/cis-disputed.js?2109231134459908';
    kommersant.antiCache.jsCharts = 'https://iy.kommersant.ru/ContentFlex/js/charts.new2021.js?2202141653190991';
    kommersant.antiCache.jsWidgets = 'https://iy.kommersant.ru/ContentFlex/js/widgets.new2021.js?2409161717291205';
    kommersant.antiCache.jsHighmapsWorldDisputed = 'https://iy.kommersant.ru/ContentFlex/js/highmaps/world-disputed.js?2109231134459908';
</script>
<script>
    window.__storage__ = window.__storage__ || {}
    window.__storage__.lentaBanners = {
        businessAnnounce: " &lt;!--197--&gt; &lt;!--AdFox START--&gt; &lt;!--kommersant--&gt; &lt;!--Площадка: Kommersant_redesign / 0Десктоп / 3й анонс в ленте--&gt; &lt;!--Категория: &lt;не задана&gt;--&gt; &lt;!--Тип баннера: 3й анонс в ленте--&gt; &lt;!--197--&gt;  &lt;div id=&quot;adfox_162799247887971226&quot;&gt;&lt;/div&gt; &lt;script&gt;   window.kommersant.adv(   () =&gt; {     window.yaContextCb.push(() =&gt; {         Ya.adfoxCode.create(         {             ownerId: 1092,             containerId: &#39;adfox_162799247887971226&#39;,             params: Object.assign({ p1: &#39;cqgxq&#39;, p2: &#39;hhrr&#39; }, window.puids || {})         },         [&#39;desktop&#39;,&#39;phone&#39;,&#39;tablet&#39;],         {             tabletWidth: 1197.99,             phoneWidth: 1197.99,             isAutoReloads: false         });     });   },   () =&gt; {}); &lt;/script&gt; ",
        twoAnnounces: [{"Id":2602,"ProfileId":1,"Position":1,"Type":1,"DocId":7180467,"Title":"Для тех, кто понимает в настоящей роскоши","Subtitle":"","Link":null,"IsSelfLink":false,"ImageSrc":null,"Enabled":true,"Category":"Промо","AdvDescription":null},{"Id":2652,"ProfileId":1,"Position":2,"Type":1,"DocId":7196629,"Title":"Кто владеет аудиторией, тот повелевает рынком","Subtitle":"Участники рекламной отрасли обсудили эволюцию стратегий в обществе постпотребления.","Link":null,"IsSelfLink":false,"ImageSrc":null,"Enabled":true,"Category":"Промо","AdvDescription":null}]
    }
</script>
<script async="" src="https://iy.kommersant.ru/ContentFlex/Redesign2020/kom2021.lentaVue.js?2409301708092629"></script>
<script>
    window.kommersant.regionId = 77;
</script>
<!-- common scripts end-->
<!--200-->
<script>window.yaContextCb = window.yaContextCb || []</script>
<script async="" src="https://yandex.ru/ads/system/context.js"></script>
<!--204-->
<script>
        window.kommersant.backend.adv = {
            180: '\r\n\u003c!--180--\u003e\r\n\r\n\u003c!--AdFox START--\u003e\r\n\u003c!--kommersant--\u003e\r\n\u003c!--Площадка: Kommersant_redesign / 0Десктоп / БА2--\u003e\r\n\u003c!--Категория: \u003cне задана\u003e--\u003e\r\n\u003c!--Тип баннера: СБА_БА--\u003e\r\n\u003c!--180--\u003e\r\n\u003cdiv id=\"adfox_161707797679975629\"\u003e\u003c/div\u003e\r\n\u003cscript\u003e\r\nwindow.kommersant.adv(\r\n  () =\u003e {\r\n    window.yaContextCb.push(() =\u003e {\r\n    Ya.adfoxCode.createScroll({\r\n        ownerId: 1092,\r\n        containerId: \u0027adfox_161707797679975629\u0027,\r\n        params: Object.assign(\r\n            {\r\n                p1: \u0027corsv\u0027,\r\n                p2: \u0027hedx\u0027,\r\n            }, window.puids || {}\r\n        ),\r\n    }, [\u0027desktop\u0027], {\r\n        tabletWidth: 1197.99,\r\n        phoneWidth: 1197.99,\r\n        isAutoReloads: false\r\n    })\r\n});\r\n  },\r\n  () =\u003e {\r\n    /* AdFox for members */\r\n  }\r\n);\r\n\r\n\u003c/script\u003e',
        };
    </script>
</head>
<body>
<svg aria-hidden="true" style="position: absolute; width: 0; height: 0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><symbol id="vicon-burger" viewbox="0 0 30 30"><path d="M25 6v4H5V6h20zM5 17h20v-4H5v4zm0 7h20v-4H5v4z"></path></symbol><symbol id="vicon-fm" viewbox="0 0 30 30"><path d="M24.25 16.21 20 18.34v-6.68l4.25 2.13c1 .5 1 1.92 0 2.42zm-9.7-4.96 1.2 4.56 1.18-4.56h2.24l-12.2-6.1C6.05 4.68 5 5.34 5 6.34v4.9h5.8v1.61H7.34v1.31h2.94v1.52H7.35v3.06H5v4.9c0 1 1.06 1.66 1.96 1.2l12.21-6.1H18.1v-5.72l-1.49 5.72h-1.73l-1.48-5.72v5.72h-1.92v-7.5h3.08z"></path></symbol><symbol id="vicon-main_logo" viewbox="0 0 158 20"><path d="M40 4h5v12h-4V9l-2.8 7h-1.9c-.2-.7-.5-.6-2.3-7v7h-4V4h5.5l1.8 6.6L40 4zm13.3 6.6L51.5 4H46v12h4V9c1.8 6.4 2 6.3 2.3 7h2c0-.3 2.6-6.6 2.7-7v7h4V4h-5l-2.7 6.6zM15.7 0H10L5 5.6V0H0v16h5v-5.1l1.5-1.6 4 6.7h6L9.8 6l5.8-6zM29 10c0 4-2.5 6.3-6.6 6.3-4 0-6.5-2.3-6.5-6 0-3.9 2.4-6.2 6.5-6.2 4 0 6.6 2.4 6.6 6zm-4.3 0c0-1.8-1-3.1-2.2-3.1-1.7 0-2.3 1.6-2.3 3.2 0 3 1.4 3.4 2.2 3.4 1 0 2.3-.6 2.3-3.4zM158 12c0 3-2.7 4-5 4h-7V7h-3V4h7v4h3c3.5 0 5 2.1 5 4zm-4 0c0-1.2-1.1-1.4-2.1-1.4h-1.7v2.7h1.7c1 0 2.1-.1 2.1-1.3zm-24-5h4v9h4V7h4V4h-12v3zm-14 7.5c0 .6 0 1 .6 1.5h-4.7l-.2-1.5-.3.2a5.8 5.8 0 0 1-4.3 1.6c-2 0-4-.9-4-3.4 0-3.1 3-3.5 5.3-3.8 1.7-.2 3-.3 3-1.4 0-.7-.6-1.2-1.7-1.2-1 0-1.6.4-1.8 1.2h-4.2c.2-2.4 2.2-3.6 6.3-3.6 5.4 0 6 2 6 4.8v5.6zm-4.5-4-.3.2a7 7 0 0 1-1.6.5c-1.1.2-2.1.4-2.1 1.6 0 .7.7 1.2 1.7 1.2 2 0 2.3-1.6 2.3-3.1v-.3zM125 9h-4V4h-4v12h4v-4h4v4h4V4h-4v5zm-36 1.1c0 4.6-2.4 5.9-5 5.9a5 5 0 0 1-2-.5c-.3-.2-1-.5-1.6-1.1L80 14v6h-4V4h4v2c.6-1.4 2.6-1.9 3.9-1.9 3.7 0 5 3.2 5 6zm-4.3 0c0-1.8-.9-3-2.3-3-1.3 0-2.1 1.3-2.1 3 0 1.8.8 3 2.1 3 1.4 0 2.3-1.2 2.3-3zm-18.4.9v.3c0 1.4 1.1 2.5 2.6 2.5a2 2 0 0 0 1.7-.8h4.2c-1.2 3-4.7 3.3-6.2 3.3-4 0-6.6-2.4-6.6-6s2.7-6.2 6.5-6.2c4.2 0 6.8 2.6 6.8 6.9h-9zm0-2H71c0-1.3-1-2.3-2.3-2.3-1.5 0-2.4.9-2.4 2.3zM96 13.6c-1.4 0-2.3-1.1-2.3-3.2C93.7 7.5 95 7 96 7c1 0 1.8.7 2 1.7h4.3C101.9 5.8 99.6 4 96 4c-4 0-6.6 2.4-6.6 6.2 0 3.6 2.6 6 6.6 6 2.1 0 5.6-.6 6.3-4.3H98c-.3 1-1 1.5-2 1.5z"></path></symbol><symbol id="vicon-rarrow" viewbox="0 0 30 30"><path d="M9.22.33c.85-.59 2.02-.38 2.61.47l9.38 13.48c.45.66.44 1.54-.03 2.18l-9.37 12.77a1.87 1.87 0 1 1-3.03-2.22L17.36 15 8.76 2.94a1.88 1.88 0 0 1 .46-2.6z"></path></symbol><symbol id="vicon-regions" viewbox="0 0 30 30"><path d="M15.1 5C19 5 22 8 22 11.9c0 4.3-6.9 13.1-6.9 13.1s-6.8-8.7-6.8-13.1C8.3 8 11.3 5 15 5zm0 10a3.1 3.1 0 1 0 0-6.2 3.1 3.1 0 0 0 0 6.2z"></path></symbol><symbol id="vicon-search" viewbox="0 0 30 30"><path d="m24.55 22.97-5-5.01a8.09 8.09 0 1 0-1.58 1.58l5 5.02c.53.52 1.3.6 1.74.15s.37-1.21-.16-1.74zM13.1 18.68a5.6 5.6 0 1 1 0-11.2 5.6 5.6 0 0 1 0 11.2z"></path></symbol></svg>
<div id="counters-top" style="position: absolute; visibility: hidden">
<script>
(function () {
  window.kommersantAnalytics = {
    adblock: '',
    audio: 'No',
    authors: '',
    date: '',
    liveinternet: 'kommersant',
    mainpage: 'Поиск',
    paid: 'No',
    photo: 'No',
    publishing: '',
    region: '',
    rubrics: '',
    themegroups: '',
    themes: '',
    department:'none',
    userId: String(window.kommersant?.user.data.UserId || 'none'),
    userType: 'none',
  };
  var advad = new Image();
  advad.onload = function () {
    window.kommersantAnalytics.adblock = 'No';
  };
  advad.onerror = function () {
    window.kommersantAnalytics.adblock = 'Yes';
  };
  advad.src = 'https://iy.kommersant.ru/ContentFlex/images/adv.gif';
})();
</script>
<!-- Kommersant -->
<script>
function counterKommersant() {
//new Image().src = '//www.kommersant.ru/headerfooter/counterA?p=0&ref=' + escape(document.referrer) + '&rnd=' + Math.floor(Math.random() * 1000000000);
}
function counterKommersantRead() {

}
counterKommersant();
counterKommersantRead();
</script>
<noscript>
</noscript>
<!-- /Kommersant -->
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">
var _tmr = window._tmr || (window._tmr = []);
_tmr.push({id: "84394", type: "pageView", start: (new Date()).getTime()});
(function (d, w, id) {
if (d.getElementById(id)) return;
var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window, "topmailru-code");
</script><noscript><div>
<img alt="" src="//top-fwz1.mail.ru/counter?id=84394;js=na" style="border:0;position:absolute;left:-9999px;"/>
</div></noscript>
<!-- //Rating@Mail.ru counter -->
<!--LiveInternet counter-->
<script>
function counterLiveInternet() {
  new Image().src = "//counter.yadro.ru/hit" + (window.kommersantAnalytics.liveinternet ? ";" + window.kommersantAnalytics.liveinternet : "") + "?r" + escape(document.referrer) + ((typeof (screen) == "undefined") ? "" : ";s" + screen.width + "*" + screen.height + "*" + (screen.colorDepth ? screen.colorDepth : screen.pixelDepth)) + ";u" + escape(document.URL) + ";h" + escape(document.title.substring(0, 80)) + ";" + Math.random();
}
counterLiveInternet();
</script>
<noscript>
<img alt="" height="1" src="//counter.yadro.ru/hit;kommersant" width="1"/>
</noscript>
<!--/LiveInternet-->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
  var yaParams = {

      department: 'none',

};
</script>
<script type="text/javascript">
  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

  ym(153166, "init", {
    clickmap:true,
    trackLinks:true,
    accurateTrackBounce:true,
    trackHash:true,
    params: yaParams
  });

  window.kommersant?.user.ready.then(() => {
    if (window.kommersant.user.data.UserId) {
      ym(153166, 'setUserID', window.kommersant.user.data.UserId);
      ym(153166, 'params', { 'UserID': window.kommersant.user.data.UserId });
    }
  });
</script>
<noscript><div><img alt="" src="https://mc.yandex.ru/watch/153166" style="position:absolute; left:-9999px;"/></div></noscript>
<!-- /Yandex.Metrika counter -->
<img id="advad" src="https://iy.kommersant.ru/ContentFlex/images/adv.gif" style="display: none"/>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-TKM0FJ12D1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());
  gtag('config', 'G-TKM0FJ12D1', window.kommersant?.utils.getAnalyticsObjectGtag() || {});

  window.kommersant?.user.ready.then(() => {
    if(window.kommersant.user.data.UserId) {
      gtag('config', 'G-TKM0FJ12D1',{ user_id: window.kommersant.user.data.UserId });
      gtag('set', { user_id: window.kommersant.user.data.UserId });
    }
  });
</script>
<!-- tns-counter.ru -->
<script>
function counterTnsNew() {
  const matchesLkuid = document.cookie.match(/(?<!\w)lkuid=([^;]*)/);
  const lkuid = matchesLkuid ? matchesLkuid[1] : '';
  const matchesSessionId = document.cookie.match(/(?<!\w)kommersantSessionId=([^;]*)/);
  let sessionId;
  if (matchesSessionId) {
    sessionId = matchesSessionId[1];
  } else {
    const size = 16;
    let seed = '';
    sessionId = '';
    for (let i = 48; i <= 122; i += (i === 57 ? 40 : 1)) {
      seed += String.fromCharCode(i);
    }
    for (let i = 0; i < size; i += 1) {
      sessionId += seed.charAt(Math.floor(Math.random() * seed.length));
    }
    document.cookie = 'kommersantSessionId=' + sessionId;
  }
  const idlc = window.doc && window.doc.id || null;
  const ver = 0;
  const type = (window.doc && window.doc.id) ? 4 : 0;
  let url = '//tns-counter.ru/e/ec01';
  url += '&cid=kommersant_ru';
  url += '&typ=1';
  url += '&tms=kommersant_ru';
  url += '&idc=155';
  url += '&uid=' + sessionId;
  url += '&hid=' + lkuid;
  url += idlc ? '&idlc=' + idlc : '';
  url += '&ver=' + ver;
  url += '&type=' + type;
  fetch(url, { credentials: 'include' }).catch(() => false);
}
counterTnsNew();
</script>
<noscript>
<img alt="" height="1" src="//tns-counter.ru/e/ec01&amp;cid=kommersant_ru&amp;typ=1&amp;tms=kommersant_ru&amp;idc=155&amp;ver=0&amp;type=0" width="1"/>
</noscript>
<!--/tns-counter.ru -->
<!-- tns-counter.ru -->
<script>
function counterTnsOld() {
  new Image().src = '//tns-counter.ru/V13a***R>' + document.referrer.replace(/\*/g, '%2a') + '*kommersant_ru/ru/CP1251/tmsec=komm_junk/' + Math.floor(Math.random() * 900000000 + 100000000);
}
counterTnsOld();
</script>
<noscript>
<img alt="" height="1" src="//tns-counter.ru/V13a****kommersant_ru/ru/CP1251/tmsec=komm_junk/" width="1"/>
</noscript>
<!--/tns-counter.ru -->
</div>
<script>
function countersUpdate() {
  counterKommersant();
  counterKommersantRead();

  try {
    _tmr.push({id: '84394', type: 'pageView', url: document.URL, start: (new Date()).getTime()});
  } catch (ignore) {}

  counterLiveInternet();

  (function () {
    var yaParams = {};
    window.kommersantAnalytics.rubrics && (yaParams.rubric = window.kommersantAnalytics.rubrics);
    window.kommersantAnalytics.publishing && (yaParams.publication = window.kommersantAnalytics.publishing);
    window.kommersantAnalytics.themes && (yaParams.theme = window.kommersantAnalytics.themes);
    window.kommersantAnalytics.themegroups && (yaParams.maintheme = window.kommersantAnalytics.themegroups);
    window.kommersantAnalytics.department && (yaParams.department = window.kommersantAnalytics.department);
    try {
      ym(153166, 'params', yaParams);
      ym(153166, 'hit', window.location.pathname + window.location.search + window.location.hash, {
        params: yaParams
      });
    } catch (ignore) {}
  })();

  (function () {
    try {
      gtag('event', 'page_view', window.kommersant?.utils.getAnalyticsObjectGtag() || {});
    } catch (ignore) {}
  })();

  counterTnsNew();

  counterTnsOld();


}
</script>
<!--190-->
<!--AdFox START-->
<!--kommersant-->
<!--Площадка: Kommersant_redesign / 0Десктоп / Fullscreen-->
<!--Категория: <не задана>-->

Напишем функцию, которая будет собирать все ссылки на новости по запросу.

In [ ]:
def get_all_links(query):
    url = 'https://www.kommersant.ru/search/results'
    params = {
        'search_query': query
    }
    res = requests.get(url, params)
    soup = BeautifulSoup(res.text)
    refs = soup.find_all('a', 'uho__link')

    links_list = []
    for ref in refs:
        links_list.append(ref.get('href'))
    # print(links_list)
    # print(len(links_list))

    links_set = set(links_list)

    print(len(links_set))

    print(links_set)

    full_links = list(map(lambda x: 'https://www.kommersant.ru' + x, links_set))

    return full_links

all_links = get_all_links('python')
print(all_links)

10
{'/doc/7183751?query=python', '/doc/7028634?query=python', '/doc/6892200?query=python', '/doc/6865882?query=python', '/doc/6851475?query=python', '/doc/6864167?query=python', '/doc/6835746?query=python', '/gallery/2747165?query=python&sids=1159624', '/doc/6835085?query=python', '/doc/6835547?query=python'}
['https://www.kommersant.ru/doc/7183751?query=python', 'https://www.kommersant.ru/doc/7028634?query=python', 'https://www.kommersant.ru/doc/6892200?query=python', 'https://www.kommersant.ru/doc/6865882?query=python', 'https://www.kommersant.ru/doc/6851475?query=python', 'https://www.kommersant.ru/doc/6864167?query=python', 'https://www.kommersant.ru/doc/6835746?query=python', 'https://www.kommersant.ru/gallery/2747165?query=python&sids=1159624', 'https://www.kommersant.ru/doc/6835085?query=python', 'https://www.kommersant.ru/doc/6835547?query=python']

Но мы же собрали только одну страницу? Хотим ВСЕ новости

In [ ]:
def get_all_links(query, pages):
    url = 'https://www.kommersant.ru/search/results'
    all_links = []
    params = {
        'search_query': query
    }
    for i in range(1, pages+1):
        params['page'] = i
        res = requests.get(url, params)
        soup = BeautifulSoup(res.text)
        # print(res.text)
        time.sleep(0.2)

        refs = soup.find_all('a', class_='uho__link')
        links_list = []

        for ref in refs:
            links_list.append(ref.get('href'))

        links_set = set(links_list)
        full_links = list(map(lambda x: 'https://www.kommersant.ru' + x, links_set))

        all_links += full_links
    return all_links

links = get_all_links('python', 4)
print(len(links))
print(links)

31
['https://www.kommersant.ru/doc/7183751?query=python', 'https://www.kommersant.ru/doc/7028634?query=python', 'https://www.kommersant.ru/doc/6892200?query=python', 'https://www.kommersant.ru/doc/6865882?query=python', 'https://www.kommersant.ru/doc/6851475?query=python', 'https://www.kommersant.ru/doc/6864167?query=python', 'https://www.kommersant.ru/doc/6835746?query=python', 'https://www.kommersant.ru/gallery/2747165?query=python&sids=1159624', 'https://www.kommersant.ru/doc/6835085?query=python', 'https://www.kommersant.ru/doc/6835547?query=python', 'https://www.kommersant.ru/doc/6745421?query=python', 'https://www.kommersant.ru/doc/6760965?query=python', 'https://www.kommersant.ru/doc/6715450?query=python', 'https://www.kommersant.ru/doc/6595306?query=python', 'https://www.kommersant.ru/doc/6679534?query=python', 'https://www.kommersant.ru/doc/6595899?query=python', 'https://www.kommersant.ru/doc/6550819?query=python', 'https://www.kommersant.ru/doc/6713963?query=python', 'https://www.kommersant.ru/doc/6621033?query=python', 'https://www.kommersant.ru/doc/6535845?query=python', 'https://www.kommersant.ru/doc/6367262?query=python', 'https://www.kommersant.ru/doc/6312197?query=python', 'https://www.kommersant.ru/doc/6311661?query=python', 'https://www.kommersant.ru/doc/6443954?query=python', 'https://www.kommersant.ru/doc/6394753?query=python', 'https://www.kommersant.ru/doc/6310903?query=python', 'https://www.kommersant.ru/doc/6296993?query=python', 'https://www.kommersant.ru/doc/6378117?query=python', 'https://www.kommersant.ru/doc/6312170?query=python', 'https://www.kommersant.ru/doc/6296079?query=python', 'https://www.kommersant.ru/doc/6282292?query=python']

А теперь отдельной функцией по этим ссылкам получим датафрейм с информацией о новостях.

In [ ]:
def get_kom_news(links):
    rows = []
    for link in links:
        soup = BeautifulSoup(requests.get(link).text)
        # print(link)
        time.sleep(0.2)
        date = pd.to_datetime(soup.find('time', 'doc_header__publish_time').get('datetime'))
        title = soup.find('h1', 'doc_header__name').text.strip()
        text = soup.find_all(class_='doc__text')  # текст бывает в div и в p
        full_text = '\n'.join(map(lambda x: x.text, text))
        row = {'date': date, 'title': title, 'text': full_text.strip()}
        rows.append(row)
    return pd.DataFrame(rows).reset_index(drop=True)

In [ ]:
kom_news = get_kom_news(links)
kom_news

,date,title,text
0,2024-09-30 00:00:01+03:00,Карта компетенций тестировщика по таксономии h...,
1,2024-09-09 16:54:26+03:00,Полное погружение в ИТ: «Школа 21» объявила пр...,В Нижнем Новгороде стартовал набор на обучение...
2,2024-08-13 17:43:41+03:00,В Чувашии выделят 45 млн руб. на создание Цент...,На базе Шумерлинского политехнического технику...
3,2024-08-01 16:57:26+03:00,IТ-компании взялись за гуманитариев,"Навыки программирования, анализа данных и рабо..."
4,2024-07-24 15:46:59+03:00,Solar appScreener 3.14.9: расширенные возможно...,"ГК «Солар», архитектор комплексной безопасност..."
5,2024-07-30 17:14:27+03:00,Градиентный бустинг в случайном лесу,Инфляция — один из ключевых показателей эконом...
6,2024-07-15 15:14:33+03:00,Спрос на услуги ИТ-специалистов вырос на 28% в...,В июне 2024 года спрос на услуги программистов...
7,2024-07-19 00:00:00+03:00,"«Господь Бог создал людей, президент Линкольн ...",19 июля 1814 года родился изобретатель «бараба...
8,2024-07-14 13:25:17+03:00,«Авито Услуги»: за полгода в Екатеринбурге спр...,В июне спрос на услуги программистов в Екатери...
9,2024-07-15 11:42:57+03:00,Пермские инженеры создали технологию на базе н...,Инженеры из пермского ООО «Дабл Ю Экспо» созда...
10,2024-06-04 12:23:46+03:00,Искусственный интеллект готовят авансом,В России вместе с популярностью нейросетей рас...
11,2024-06-10 16:15:55+03:00,Биомедицина будущего,В 2022 году Сеченовский университет Минздрава ...
12,2024-05-23 17:50:50+03:00,Смольный пообещал на лето трудоустроить не мен...,Не менее 11 тыс. подростков обещают трудоустро...
13,2024-03-28 00:01:00+03:00,«Люди стали более внимательно и требовательно ...,Последние полтора года многие российские предп...
14,2024-05-22 00:01:00+03:00,Квантовый прыжок в технологии,ДОМ.РФ как институт развития жилищного строите...
15,2024-03-28 00:00:00+03:00,В приоритете — опыт,"Многие российские IT-компании, несмотря на сер..."
16,2024-03-06 00:01:00+03:00,"«Внедрять и развивать инновации нужно тем, кто...",IT-индустрия зачастую все еще воспринимается м...
17,2024-05-22 00:05:00+03:00,Абитуриенты рвутся в IT,IT-направления среди поступающих в вузы с кажд...
18,2024-04-09 17:41:53+03:00,Открытый код нараспашку,На фоне ухода из России западных вендоров обще...
19,2024-02-29 20:46:49+03:00,Опыта больше,"Несмотря на потребность в кадрах, многие IT-ко..."
20,2023-12-21 00:01:00+03:00,Без умений нет труда,На российском рынке труда растет популярность ...
21,2023-11-01 13:41:41+03:00,«Цифровая Россия» запускает проект переподгото...,Партия «Единая Россия» в рамках партпроекта «Ц...
22,2023-11-01 13:13:53+03:00,Рынок ИТ-найма сыграл по новым правилам,О тенденциях в ИТ-рекрутменте рассказала дирек...
23,2024-01-10 12:37:12+03:00,Карьерный трек потребовал курс,Россияне в январские праздники скупали курсы «...
24,2023-12-14 00:01:00+03:00,Безработица ниже некуда,"Реальная зарплата в этом году выросла на 7%, з..."
25,2023-10-30 21:25:58+03:00,Нейросетевая библиотека для быстрых аэродинами...,В Московском авиационном институте разработали...
26,2023-10-24 16:30:10+03:00,Какой язык программирования выбрать в 2024 году,31 октября 2023 года в 12:00 на YouTube-канале...
27,2023-12-04 19:00:30+03:00,"«Мы видим больше креатива вокруг этой области,...",5 декабря прошло первое мероприятие зимнего ци...
28,2023-11-01 13:09:11+03:00,Нижегородских ветеранов СВО будут переучивать ...,Нижегородская область вошла в число пилотных р...
29,2023-10-24 00:00:01+03:00,Не только «цифра»,Расширение инструментов для поиска кандидата с...
30,2023-10-18 07:59:10+03:00,Жители Прикамья смогут обучиться аналитике данных,МТС открыла бесплатное обучение для жителей Пе...

Проблемы веб-скрапинга

- Огромное многообразие сайтов и у каждого сайта своя структура

- Сайты постоянно меняются

- Контент сайта может формироваться динамически (тогда его содержимое из HTML не достать)

- Сайты могут использовать различные средства защиты, которые могут усложнять сбор информации.